FROM alpine:latest AS certs
RUN apk --no-cache add ca-certificates

FROM scratch
COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY warhutv /warhutv
COPY frontend/dist /frontend/dist
COPY data/config.example.json /data/config.json

EXPOSE 3000
CMD ["/warhutv"]
